source "https://rubygems.org"
gem "rails", "~> 5.0.0", ">= 5.0.0.1"
gem "mysql2", ">= 0.3.18", "< 0.5"
gem "puma", "~> 3.0"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.2"
gem "jquery-rails"
gem "turbolinks", "~> 5"
gem "jbuilder", "~> 2.5"
gem "bootstrap-sass"
gem "devise"
gem "redis", "~> 3.0"
gem "i18n-js", ">= 3.0.0.rc12"
gem "nested_form"
gem "carrierwave", ">= 1.0.0.beta", "< 2.0"
gem "mini_magick"
gem "settingslogic"
gem "bootstrap-datepicker-rails"
gem "font-awesome-rails"
gem "bootstrap-kaminari-views"
gem "kaminari"
gem "cancancan", "~> 1.10"
gem "selectize-rails"
gem "ckeditor"
gem "remotipart", "~> 1.2"
gem "jasny-bootstrap-rails"
gem "unparser"
gem "chewy"
gem "paranoia", "~> 2.2"
group :development, :test do
  gem "pry"
  gem "faker", "1.4.2"
end

group :development do
  gem "web-console"
  gem "listen", "~> 3.0.5"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
